FROM node:20 AS base

FROM base as build
WORKDIR /app
RUN npm i -g pnpm
COPY package.json pnpm-lock.yaml ./
RUN pnpm install
COPY . .
RUN pnpm build

FROM base as release
WORKDIR /app
RUN npm i -g pnpm

COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/.next ./.next

CMD ["pnpm", "start"]